#### For login shells ###

# Set the default editor to Neovim
export EDITOR=nvim


# Load personal secrets
if [ -f "$HOME/.zprofile.secrets" ]; then
  source "$HOME/.zprofile.secrets"
fi

export PATH=$PATH:~/.local/bin
export PATH=$PATH:~/bin
export PATH=$PATH:/usr/local/bin

export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="/opt/homebrew/lib/ruby/gems/3.3.0/bin:$PATH"

# Rust
export PATH=$PATH:$HOME/.cargo/bin

# Java
export PATH="$HOME/.jenv/bin:$PATH"

#export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
#export JAVA_HOME="/opt/homebrew/opt/openjdk"
#export JAVA_HOME=$(/usr/libexec/java_home -v 17)
export PATH=$JAVA_HOME/bin:$PATH

# Go
export PATH="$PATH:$(go env GOPATH)/bin"

# Android
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH

export PATH=$PATH:'/Applications/Visual Studio Code.app/Contents/Resources/app/bin'

export PATH="$HOME/.local/bin:$PATH"

# source a file containing environment specific entries if it exists.
[ -f ~/.zprofile.local ]  && source ~/.zprofile.local

export AWS_DEFAULT_PROFILE=ara-personal
# source a file containing environment specific entries if it exists
eval "$(/opt/homebrew/bin/brew shellenv)"
