#### Interactive shell settings ####

# Use vi keybindings in the shell
set -o vi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git docker aws extract virtualenv vi-mode)

# Cursor switching on mode change
VI_MODE_SET_CURSOR=true

# Shapes per mode (DECSCUSR codes)
# 0/1/2 = block, 3/4 = underline, 5/6 = bar
VI_MODE_CURSOR_NORMAL=2     # block in Normal (vicmd)
VI_MODE_CURSOR_INSERT=6     # bar in Insert (viins)
VI_MODE_CURSOR_VISUAL=2     # block in Visual
VI_MODE_CURSOR_OPPEND=0     # (optional) blinking block while an operator is pending

source $ZSH/oh-my-zsh.sh

# setup vi editing mode
bindkey -v
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/arajuljulian/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions

eval "$(jenv init -)"


###################################
####### Useful functions ##########
###################################
function bb { open -a /Applications/BBEdit.app $*; }
function aws-personal { aws --profile ara-personal $*; }
function ai() {
  openai api completions.create -m gpt-4o-mini -p "$*"
}
# Useful aliases
alias dd='cd ~/Development'
alias ddp='dd; cd personal'
alias ddc='dd; cd configs'
alias guru='ddp; cd tregglio/guru'
alias my_ec2_instance='ssh -i ~/.ssh/ara-aws-key-oregon.pem ec2-user@54.214.77.218'
alias pi-hole='ssh -i ~/.ssh/id_rsa_personal arajuljulian@192.168.7.251'
alias zzz='source ~/.zshrc && source ~/.zprofile'
alias tmux='tmux -u'
alias k='kubectl'
alias lg='lazygit'

# Load local, machine-specific extras (ignored by git)
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
